config/routes.rb
Rails.application.routes.draw do
  resources :camps
  resources :companies
  resources :badges
  devise_for :users
  resources :users
  root to: 'camps#index'
  post 'camps/autosave', to: 'camps#autosave'
  get '/camp/statistics', to: 'camps#statistics'
  get '/camp/payments', to: 'camps#payments'
  get 'downloads', to: 'application#downloads'
end

app/models/camp.rb
require 'csv'

class Camp < ApplicationRecord
  belongs_to :company
  has_many :seasonships
  has_many :season_types, through: :seasonships
  has_many :camp_shifts
  has_many :geotags
  has_many :group_leaders
  has_many :reviews
  has_many :review_roles, through: :reviews
  has_many :categorizations
  has_many :camp_categories, through: :categorizations
  has_many :taggizations
  has_many :geotags, through: :taggizations
  belongs_to :user
  belongs_to :iteration

  accepts_nested_attributes_for :reviews, allow_destroy: true
  accepts_nested_attributes_for :group_leaders, allow_destroy: true
  accepts_nested_attributes_for :camp_shifts, allow_destroy: true

  def self.as_csv
    CSV.generate do |csv|
      columns = %w(id url name facebook vk incamp_url ml_url dt_url bc_url pd_url inlearno_url created_at updated_at company_id preview program study accommodation meal security pricing adds latitude longitude starting_age finish_age foundation_year kids_in_camp kids_in_group leaders_per_group promo_day photos video_links comment schedule user_id presentation has_incamp_price group_leader_anounce)
      csv << columns.map(&:humanize)
      Camp.find_each do |c|
        csv << c.attributes.values_at(*columns)
      end
    end
  end

  def self.next_camp_for_edition(user_id)
    # should be added choosing the same organization later
    camp = Camp.where('user_id = ? AND (is_finished IS NULL OR is_finished = FALSE)', user_id) #already started camp
    if camp.blank?
      select_clause = 'DISTINCT camps.*'
      from_clause = 'camps, camps as other_camps'
      where_clause = 'camps.company_id = other_camps.company_id and camps.user_id = ? and camps.is_finished = TRUE and other_camps.is_finished IS NULL'
      camp = Camp.select(select_clause).where(where_clause, user_id).from(from_clause).all
      camp = Camp.where('is_finished IS NULL') if camp.blank?
      return nil if camp.blank?
    end
    camp.first
  end

  def fullness
    score = 0
    max_score = 37
    score += 1 unless presentation.nil?
    score += 2 unless preview.blank?
    score += 2 unless program.blank?
    score +=2 unless study.blank?
    score +=2 unless schedule.blank?
    score +=2 unless accommodation.blank?
    score +=1 unless meal.blank?
    score +=2 unless security.blank?
    score +=1 unless seasonships.blank?
    score +=1 unless camp_categories.blank?
    score +=1 unless pricing.blank?
    score +=1 unless adds.blank?
    score +=1 unless latitude.blank?
    score +=1 unless longitude.blank?
    score +=1 unless geotags.blank?
    score +=1 unless starting_age.blank?
    score +=1 unless finish_age.blank?
    score +=1 unless foundation_year.blank?
    score +=1 unless kids_in_camp.blank?
    score +=1 unless kids_in_group.blank?
    score +=1 unless leaders_per_group.blank?
    score +=1 unless promo_day.nil?
    score +=1 unless photos.blank?
    score +=1 unless video_links.blank?
    score +=2 unless group_leader_anounce.blank?
    score +=2 unless group_leaders.blank?
    score +=2 unless reviews.blank?
    score +=1 unless is_finished.nil?
    full = score.to_f / max_score
    fl = full * 100
    return fl.to_i
  end
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :badge
  has_many :users
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :authenticate_user!

  def index
    q = params[:user_ids].blank? ? Camp.all : Camp.where('user_id in (?)', params[:user_ids])
    @camps = current_user.is_admin? ? q.where(is_approved: [0, nil]) : Camp.where('user_id = ? AND (is_approved IS NULL OR is_approved = FALSE)', current_user.id)

    respond_to do |format|
      format.html
      format.csv { send_data Camp.as_csv }
    end
  end

  def autosave
    @camp = Camp.find(params[:camp_id])
    params[:is_finished] = @camp.is_finished if current_user.is_admin? #only for content person is ok to change is_finished
    @camp.update_attributes(current_user.is_admin? ? camp_full_params : camp_content_params)
  end

  def statistics
  end

  def payments
    @users = User.all
  end

  def new
    if current_user.is_admin?
      @camp = Camp.new
    else
      @camp = Camp.next_camp_for_edition current_user.id
      if @camp.blank?
        flash[:warning] = 'Нет лагерей для создания. Обратитесь к администратору'
        redirect_to root_path
      else
        @camp.update_attribute(:user, current_user)
        redirect_to edit_camp_path @camp
      end

    end
  end

  def create
    @camp = Camp.create(camp_full_params)
    @camp.update_attribute(:is_finished, nil)
    @camp.user = current_user
    @camp.save
    if @camp.errors.any?
      flash.now[:warning] = @camp.errors.full_messages
      render 'new'
    else
      redirect_to root_path
    end
  end

  def update
    @camp = Camp.find(params[:id])
    params[:is_finished] = @camp.is_finished if current_user.is_admin? #only for content person is ok to change is_finished
    @camp.update_attributes(current_user.is_admin? ? camp_full_params : camp_content_params) if params[:version_number].to_i > @camp.version_number || current_user.is_admin?
    redirect_to camp_path @camp
  end

  def show
    @camp = Camp.find(params[:id])
  end

  def edit
    @camp = Camp.find(params[:id])
    if @camp.user == current_user || current_user.is_admin?
      @camp.update_attribute(:is_finished, false) unless current_user.is_admin?
    else
      flash[:warning] = 'Вы не можете редактировать этот лагерь'
      redirect_to root_path
    end

  end


  private

  def update_geotags
    unless params[:camp][:geotag_ids].blank?
      geotags = params[:camp][:geotag_ids].collect do |g|
        if g.to_i.zero?
          geotag = Geotag.create(name: g)
          geotag.id.to_s
        else
          g
        end
      end
      params[:camp][:geotag_ids] = geotags
    end
  end

  def camp_content_params
    update_geotags
    params.require(:camp).permit!
  end

  def camp_full_params
    # is_finished is absent cause only content-person should check it
    update_geotags
    params.require(:camp).permit!
  end
end

app/helpers/camps_helper.rb
module CampsHelper
  def camp_full_name_hash
    {
      url: 'Сайт лагеря',
      facebook: 'Группа в фб',
      vk: 'Группа в ВК',
      incamp_url: 'Страница на Incamp',
      ml_url: 'Страница на mir-lagerey',
      dt_url: 'Страница на deti-travel',
      inlearno_url: 'Страница на Inlearno',
      bc_url: 'Страница на best-camps',
      pd_url: 'Страница на poehali-deti',
      preview: 'Анонс лагеря',
      program: 'Общая программа',
      study: 'Обучение',
      schedule: 'Распорядок дня',
      accommodation: 'Размещение/территория',
      meal: 'Питание',
      security: 'Безопасность/медицина',
      pricing: 'Что входит в стоимость',
      adds: 'Адрес',
      latitude: 'Широта',
      longitude: 'Долгота',
      starting_age: 'С какого возраста',
      finish_age: 'До какого возраста',
      foundation_year: 'Год основания',
      kids_in_camp: 'Детей в лагере',
      kids_in_group: 'Детей в отряде',
      leaders_per_group: 'Вожатых на отряд',
      promo_day: 'Наличие дня открытых дверей',
      photos: 'Качество фотографий',
      video_links: 'Ссылки на видео',
      comment: 'Общий комментарий',
      is_finished: 'Заполнение анкеты окончено'
    }
  end

  def camp_admin_name_hash
    {
        url: 'Сайт лагеря',
        facebook: 'Группа в фб',
        vk: 'Группа в ВК',
        incamp_url: 'Страница на Incamp',
        ml_url: 'Страница на mir-lagerey',
        dt_url: 'Страница на deti-travel',
        inlearno_url: 'Страница на Inlearno',
        bc_url: 'Страница на best-camps',
        pd_url: 'Страница на poehali-deti'
    }
  end


end

app/views/camps/_admin_form.html.haml
%h1.text-center
  = @camp.name
.row
  .col-md-12
    = form_for @camp, id: 'content_form' do |f|
      .panel.panel-danger
        .panel-heading
          %h5.panel-title
            = link_to 'Заполняется администратором (показать/скрыть)'
        .panel-body
          .form-group
            %label Название организации
            = f.collection_select :company_id, Company.all.order(:name), :id, :name, {}, class: 'js-select'
          .form-group
            %label ID лагеря
            = text_field_tag :camp_id, @camp.id, class: 'form-control'
          .form-group
            %label Название лагеря
            = f.text_field :name, class: 'form-control'
          .form-group
            %label Сайт лагеря
            = f.text_field :url, class: 'form-control'
          .form-group
            %label Группа в фб
            = f.text_field :facebook, class: 'form-control'
          .form-group
            %label Группа в ВК
            = f.text_field :vk, class: 'form-control'
          .form-group
            %label Страница на Incamp
            = f.text_field :incamp_url, class: 'form-control'
          .form-group
            %label Наличие цены на Incamp
            = f.check_box :has_incamp_price
          .form-group
            %label Страница на mir-lagerey
            = f.text_field :ml_url, class: 'form-control'
          .form-group
            %label Страница на deti-travel
            = f.text_field :dt_url, class: 'form-control'
          .form-group
            %label Страница на Inlearno
            = f.text_field :inlearno_url, class: 'form-control'
          .form-group
            %label Страница на best-camps.ru
            = f.text_field :bc_url, class: 'form-control'
          .form-group
            %label Страница на poehalideti.ru
            = f.text_field :pd_url, class: 'form-control'
          .form-group
            %label Контент-менеджер
            = f.collection_select :user_id, User.where(is_archived: [nil,false]).order(:name), :id, :name, {}, {class: 'js-select'}
          .form-group
            %label Комментарий администратора
            = f.text_area :admin_comment, class: 'form-control', rows: '5'
          .form-group
            %label Итерация исправлений
            = f.collection_select :iteration_id, Iteration.all.order(:id), :id, :text, {}, {class: 'js-select'}
          .form-group
            %label Анкета прошла проверку администратора
            = f.check_box :is_approved
      .panel.panel-info
        .panel-heading
          %h5.panel-title
            = link_to 'Заполняется контент-менеджером (показать/скрыть)', '#', id: 'hiding-link'
        #admin-panel.panel-body{style: 'display: none;'}
          .form-group
            %label Наличие презентации о лагере
            = f.check_box :presentation
          .form-group
            %label Анонс лагеря
            = f.text_area :preview, class: 'form-control', rows: '20', id: 'big_field'
          .form-group
            %label Программа лагеря
            = f.text_area :program, class: 'form-control', rows: '20'
          .form-group
            %label Обучение
            = f.text_area :study, class: 'form-control', rows: '20'
          .form-group
            %label Распорядок дня
            = f.text_area :schedule, class: 'form-control', rows: '20'
          .form-group
            %label Размещение/территория
            = f.text_area :accommodation, class: 'form-control', rows: '20'
          .form-group
            %label Питание
            = f.text_area :meal, class: 'form-control', rows: '20'
          .form-group
            %label Медицина/безопасность
            = f.text_area :security, class: 'form-control', rows: '20'
          .form-group
            %label Сезон работы
            = f.collection_select :season_type_ids, SeasonType.all.order(:name), :id, :name, {}, {multiple: true, class: "js-select"}
          .form-group
            %label Категория лагеря
            = f.collection_select :camp_category_ids, CampCategory.all.order(:name), :id, :name, {}, {multiple: true, class: "js-select"}
          %fieldset
            %legend Смены в лагере
            = f.fields_for :camp_shifts do |builder|
              = render 'camp_shift_fields', f: builder, i: builder.options[:child_index]
            = link_to_add_fields 'Добавить смену', f, :camp_shifts
          .form-group
            %label Что входит в стоимость
            = f.text_area :pricing, class: 'form-control', rows: '20'
          .form-group
            %label Адрес
            = f.text_area :adds, class: 'form-control', rows: '2'
          .form-group
            %label Широта
            = f.text_field :latitude, class: 'form-control'
          .form-group
            %label Долгота
            = f.text_field :longitude, class: 'form-control'
          .form-group
            %label Геотеги лагеря
            = f.collection_select :geotag_ids, Geotag.all.order(:name), :id, :name, {}, {multiple: true, class: "js-select-new"}
          .form-group
            %label С какого возраста
            = f.text_field :starting_age, class: 'form-control'
          .form-group
            %label До какого возраста
            = f.text_field :finish_age, class: 'form-control'
          .form-group
            %label Год основания лагеря
            = f.text_field :foundation_year, class: 'form-control'
          .form-group
            %label Детей в лагере
            = f.text_field :kids_in_camp, class: 'form-control'
          .form-group
            %label Детей в отряде
            = f.text_field :kids_in_group, class: 'form-control'
          .form-group
            %label Вожатых на отряд
            = f.text_field :leaders_per_group, class: 'form-control'
          .form-group
            %label День открытых дверей
            = f.check_box :promo_day
          .form-group
            %label Качество фотографий
            = f.text_field :photos, class: 'form-control'
          .form-group
            %label Ссылки на видео
            = f.text_area :video_links, class: 'form-control', rows: '2'
          .form-group
            %label Общий комментарий
            = f.text_area :comment, class: 'form-control', rows: '20'
          %fieldset
            %legend Вожатые в лагере
            .form-group
              %label Анонс о вожатых
              = f.text_area :group_leader_anounce, class: 'form-control', rows: '3'
            = f.fields_for :group_leaders do |builder|
              = render 'group_leader_fields', f: builder, i: builder.options[:child_index]
            = link_to_add_fields 'Добавить вожатого', f, :group_leaders
          %fieldset
            %legend Отзывы о лагере
            = f.fields_for :reviews do |builder|
              = render 'review_fields', f: builder, i: builder.options[:child_index]
            = link_to_add_fields 'Добавить отзыв', f, :reviews
          .form-group
            %label Заполнение анкеты завершено
            = f.check_box :is_finished
      = f.submit 'Сохранить форму', class: 'btn btn-outline-primary'

app/views/camps/_content_form.html.haml
%h1.text-center
  = @camp.name
.row
  .col-md-12
    = form_for @camp, id: 'content_form' do |f|

      %p
        Анкета прошла проверку администратора:
        %span{style: "color: #{@camp.is_approved.blank? ? 'red' : 'green'};"}
          = @camp.is_approved.blank? ? 'Нет' : 'Да'
      .form-group
        %label Комментарий администратора
        = f.text_area :admin_comment, class: 'form-control', readonly: 'true'
      .panel.panel-danger
        .panel-heading
          %h5.panel-title
            = link_to 'Заполняется администратором (показать/скрыть)', '#', id: 'hiding-link'
        #admin-panel.panel-body{style: 'display: none;'}
          .form-group
            %label Название организации
            = text_field_tag :company_id, @camp.company.name, class: 'form-control', readonly: 'true'
          .form-group
            %label ID лагеря
            = text_field_tag :camp_id, @camp.id, class: 'form-control', readonly: 'true'
          .form-group
            %label Название лагеря
            = f.text_field :name, class: 'form-control', readonly: 'true'
          .form-group
            %label Сайт лагеря
            = f.text_field :url, class: 'form-control', readonly: 'true'
          .form-group
            %label Группа в фб
            = f.text_field :facebook, class: 'form-control', readonly: 'true'
          .form-group
            %label Группа в ВК
            = f.text_field :vk, class: 'form-control', readonly: 'true'
          .form-group
            %label Страница на Incamp
            = f.text_field :incamp_url, class: 'form-control', readonly: 'true'
          .form-group
            %label
              Цена на Incamp:
              = @camp.has_incamp_price? ? 'Да' : 'Нет'
          .form-group
            %label Страница на mir-lagerey
            = f.text_field :ml_url, class: 'form-control', readonly: 'true'
          .form-group
            %label Страница на deti-travel
            = f.text_field :dt_url, class: 'form-control', readonly: 'true'
          .form-group
            %label Страница на Inlearno
            = f.text_field :inlearno_url, class: 'form-control', readonly: 'true'
          .form-group
            %label Страница на best-camps.ru
            = f.text_field :bc_url, class: 'form-control', readonly: 'true'
          .form-group
            %label Страница на poehalideti.ru
            = f.text_field :pd_url, class: 'form-control', readonly: 'true'
      .panel.panel-info
        .panel-heading
          %h5.panel-title
            Заполняется Вами
        .panel-body
          = hidden_field_tag 'version_number', '1'
          .form-group
            %label Наличие презентации о лагере
            = f.check_box :presentation
          .form-group
            %label Анонс лагеря
            = f.text_area :preview, class: 'form-control', rows: '20', onChange: 'save(event)'
          .form-group
            %label Программа лагеря
            = f.text_area :program, class: 'form-control', rows: '20', onChange: 'save(event)'
          .form-group
            %label Обучение
            = f.text_area :study, class: 'form-control', rows: '20', onChange: 'save(event)'
          .form-group
            %label Распорядок дня
            = f.text_area :schedule, class: 'form-control', rows: '20', onChange: 'save(event)'
          .form-group
            %label Размещение/территория
            = f.text_area :accommodation, class: 'form-control', rows: '20', onChange: 'save(event)'
          .form-group
            %label Питание
            = f.text_area :meal, class: 'form-control', rows: '20', onChange: 'save(event)'
          .form-group
            %label Медицина/безопасность
            = f.text_area :security, class: 'form-control', rows: '20', onChange: 'save(event)'
          .form-group
            %label Сезон работы
            = f.collection_select :season_type_ids, SeasonType.all.order(:name), :id, :name, {}, {multiple: true, class: "js-select"}
          .form-group
            %label Категория лагеря
            = f.collection_select :camp_category_ids, CampCategory.all.order(:name), :id, :name, {}, {multiple: true, class: "js-select"}
          %fieldset
            %legend Смены в лагере
            = f.fields_for :camp_shifts do |builder|
              = render 'camp_shift_fields', f: builder, i: builder.options[:child_index]
            = link_to_add_fields 'Добавить смену', f, :camp_shifts
          .form-group
            %label Что входит в стоимость
            = f.text_area :pricing, class: 'form-control', rows: '20', onChange: 'save(event)'
          .form-group
            %label Адрес
            = f.text_area :adds, class: 'form-control', rows: '2', onChange: 'save(event)'
          .form-group
            %label Широта
            = f.text_field :latitude, class: 'form-control', onChange: 'save(event)'
          .form-group
            %label Долгота
            = f.text_field :longitude, class: 'form-control', onChange: 'save(event)'
          .form-group
            %label Геотеги лагеря
            = f.collection_select :geotag_ids, Geotag.all.order(:name), :id, :name, {}, {multiple: true, class: "js-select-new"}
          .form-group
            %label С какого возраста
            = f.text_field :starting_age, class: 'form-control', onChange: 'save(event)'
          .form-group
            %label До какого возраста
            = f.text_field :finish_age, class: 'form-control', onChange: 'save(event)'
          .form-group
            %label Год основания лагеря
            = f.text_field :foundation_year, class: 'form-control', onChange: 'save(event)'
          .form-group
            %label Детей в лагере
            = f.text_field :kids_in_camp, class: 'form-control', onChange: 'save(event)'
          .form-group
            %label Детей в отряде
            = f.text_field :kids_in_group, class: 'form-control', onChange: 'save(event)'
          .form-group
            %label Вожатых на отряд
            = f.text_field :leaders_per_group, class: 'form-control', onChange: 'save(event)'
          .form-group
            %label День открытых дверей
            = f.check_box :promo_day
          .form-group
            %label Качество фотографий
            = f.text_field :photos, class: 'form-control', onChange: 'save(event)'
          .form-group
            %label Ссылки на видео
            = f.text_area :video_links, class: 'form-control', rows: '2', onChange: 'save(event)'
          .form-group
            %label Общий комментарий
            = f.text_area :comment, class: 'form-control', rows: '20', onChange: 'save(event)'
          %fieldset
            %legend Вожатые в лагере
            .form-group
              %label Анонс о вожатых
              = f.text_area :group_leader_anounce, class: 'form-control', rows: '3'
            = f.fields_for :group_leaders do |builder|
              = render 'group_leader_fields', f: builder, i: builder.options[:child_index]
            = link_to_add_fields 'Добавить вожатого', f, :group_leaders
          %fieldset
            %legend Отзывы о лагере
            = f.fields_for :reviews do |builder|
              = render 'review_fields', f: builder, i: builder.options[:child_index]
            = link_to_add_fields 'Добавить отзыв', f, :reviews
          .form-group
            %label Заполнение анкеты завершено
            = f.check_box :is_finished
      = f.submit 'Сохранить форму', class: 'btn btn-outline-primary'

app/views/camps/_show_admin_fileds.html.haml
%h3
  = camp.name
%p.font-weight-light.no_margin
  %strong
    Организация:
  = camp.company.name

- camp_admin_name_hash.each do |a, b|
  %p.font-weight-light.no_margin
    %strong
      = b
    = camp[a]

app/views/camps/check.html.haml
%h1.text-center
  = @check.name
.row
  .col-md-12
    = form_for @check, id: 'content_form' do |f|

      %p
        Анкета прошла проверку администратора:
        %span{style: "color: #{@check.is_approved.blank? ? 'red' : 'green'};"}
          = @check.is_approved.blank? ? 'Нет' : 'Да'
      .form-group
        %label Комментарий администратора
        = f.text_area :admin_comment, class: 'form-control', readonly: 'true'
      .panel.panel-danger
        .panel-heading
          %h3.panel-title
            = link_to 'Заполняется администратором (показать/скрыть)', '#', id: 'hiding-link'
        #admin-panel.panel-body{style: 'display: none;'}
          .form-group
            %label Название организации
            = text_field_tag :company_id, @check.company.name, class: 'form-control', readonly: 'true'
          .form-group
            %label ID лагеря
            = text_field_tag :camp_id, @check.id, class: 'form-control', readonly: 'true'
          .form-group
            %label Название лагеря
            = f.text_field :name, class: 'form-control', readonly: 'true'
          .form-group
            %label Сайт лагеря
            = f.text_field :url, class: 'form-control', readonly: 'true'
          .form-group
            %label Группа в фб
            = f.text_field :facebook, class: 'form-control', readonly: 'true'
          .form-group
            %label Группа в ВК
            = f.text_field :vk, class: 'form-control', readonly: 'true'
          .form-group
            %label Страница на Incamp
            = f.text_field :incamp_url, class: 'form-control', readonly: 'true'
          .form-group
            %label
              Цена на Incamp:
              = @check.has_incamp_price? ? 'Да' : 'Нет'
          .form-group
            %label Страница на mir-lagerey
            = f.text_field :ml_url, class: 'form-control', readonly: 'true'
          .form-group
            %label Страница на deti-travel
            = f.text_field :dt_url, class: 'form-control', readonly: 'true'
          .form-group
            %label Страница на Inlearno
            = f.text_field :inlearno_url, class: 'form-control', readonly: 'true'
          .form-group
            %label Страница на bestcamps
            = f.text_field :bc_url, class: 'form-control', readonly: 'true'
          .form-group
            %label Страница на poehali-deti
            = f.text_field :pd_url, class: 'form-control', readonly: 'true'
      .panel.panel-info
        .panel-heading
          %h3.panel-title
            Заполняется Вами
        .panel-body
          .form-group
            %label Наличие презентации о лагере
            = f.check_box :presentation
          .form-group
            %label Анонс лагеря
            = f.text_area :preview, class: 'form-control', rows: '20', id: 'big_field'
          .form-group
            %label Программа лагеря
            = f.text_area :program, class: 'form-control', rows: '20'
          .form-group
            %label Обучение
            = f.text_area :study, class: 'form-control', rows: '20'
          .form-group
            %label Распорядок дня
            = f.text_area :schedule, class: 'form-control', rows: '20'
          .form-group
            %label Размещение/территория
            = f.text_area :accommodation, class: 'form-control', rows: '20'
          .form-group
            %label Питание
            = f.text_area :meal, class: 'form-control', rows: '20'
          .form-group
            %label Медицина/безопасность
            = f.text_area :security, class: 'form-control', rows: '20'
          .form-group
            %label Сезон работы
            = f.collection_select :season_type_ids, SeasonType.all.order(:name), :id, :name, {}, {multiple: true, class: "js-select"}
          .form-group
            %label Категория лагеря
            = f.collection_select :camp_category_ids, CampCategory.all.order(:name), :id, :name, {}, {multiple: true, class: "js-select"}
          %fieldset
            %legend Смены в лагере
            = f.fields_for :camp_shifts do |builder|
              = render 'camp_shift_fields', f: builder, i: builder.options[:child_index]
            = link_to_add_fields 'Добавить смену', f, :camp_shifts
          .form-group
            %label Что входит в стоимость
            = f.text_area :pricing, class: 'form-control', rows: '20'
          .form-group
            %label Адрес
            = f.text_area :adds, class: 'form-control', rows: '2'
          .form-group
            %label Широта
            = f.text_field :latitude, class: 'form-control'
          .form-group
            %label Долгота
            = f.text_field :longitude, class: 'form-control'
          .form-group
            %label Геотеги лагеря
            = f.collection_select :geotag_ids, Geotag.all.order(:name), :id, :name, {}, {multiple: true, class: "js-select-new"}
          .form-group
            %label С какого возраста
            = f.text_field :starting_age, class: 'form-control'
          .form-group
            %label До какого возраста
            = f.text_field :finish_age, class: 'form-control'
          .form-group
            %label Год основания лагеря
            = f.text_field :foundation_year, class: 'form-control'
          .form-group
            %label Детей в лагере
            = f.text_field :kids_in_camp, class: 'form-control'
          .form-group
            %label Детей в отряде
            = f.text_field :kids_in_group, class: 'form-control'
          .form-group
            %label Вожатых на отряд
            = f.text_field :leaders_per_group, class: 'form-control'
          .form-group
            %label День открытых дверей
            = f.check_box :promo_day
          .form-group
            %label Качество фотографий
            = f.text_field :photos, class: 'form-control'
          .form-group
            %label Ссылки на видео
            = f.text_area :video_links, class: 'form-control', rows: '2'
          .form-group
            %label Общий комментарий
            = f.text_area :comment, class: 'form-control', rows: '20'
          %fieldset
            %legend Вожатые в лагере
            .form-group
              %label Анонс о вожатых
              = f.text_area :group_leader_anounce, class: 'form-control', rows: '3'
            = f.fields_for :group_leaders do |builder|
              = render 'group_leader_fields', f: builder, i: builder.options[:child_index]
            = link_to_add_fields 'Добавить вожатого', f, :group_leaders
          %fieldset
            %legend Отзывы о лагере
            = f.fields_for :reviews do |builder|
              = render 'review_fields', f: builder, i: builder.options[:child_index]
            = link_to_add_fields 'Добавить отзыв', f, :reviews
          .form-group
            %label Заполнение анкеты завершено
            = f.check_box :is_finished
      = f.submit 'Сохранить форму', class: 'btn btn-info'

app/views/camps/index.html.haml
= link_to "Создать новый", new_camp_path, class: 'btn btn-outline-primary btn-sm', style: 'margin-top: 10px;'
%h1.text-center Все лагеря

- if current_user.is_admin?

  = link_to "Статистика сайта", "camp/statistic"
  = link_to "Список пользователей", "/users/index"  
  = form_tag camps_path, method: :get do
    .form-group
      = label_tag :user_ids, "Отфильтровать по пользователям"
      = select_tag :user_ids, options_from_collection_for_select(User.all.order(:name), :id, :name, params[:user_ids]), multiple: true, class: "form-control form-control-sm js-select"

    = submit_tag "Найти пользователя", name: nil, class: "btn btn-primary btn-sm"


= link_to "Создать новый", new_camp_path

= render @camps