config/routes.rb
Rails.application.routes.draw do
  resources :camps
  resources :companies
  resources :badges
  devise_for :users
  resources :users
  root to: 'camps#index'
  post 'camps/autosave', to: 'camps#autosave'
  get '/camp/statistics', to: 'camps#statistics'
  get '/camp/payments', to: 'camps#payments'
  get 'downloads', to: 'application#downloads'
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_one_attached :main_picture
  has_one :status
end

app/models/camp.rb
require 'csv'

class Camp < ApplicationRecord
  belongs_to :company
  has_many :seasonships
  has_many :season_types, through: :seasonships
  has_many :camp_shifts
  has_many :geotags
  has_many :group_leaders
  has_many :reviews
  has_many :review_roles, through: :reviews
  has_many :categorizations
  has_many :camp_categories, through: :categorizations
  has_many :taggizations
  has_many :geotags, through: :taggizations
  belongs_to :user
  belongs_to :iteration

  accepts_nested_attributes_for :reviews, allow_destroy: true
  accepts_nested_attributes_for :group_leaders, allow_destroy: true
  accepts_nested_attributes_for :camp_shifts, allow_destroy: true

  def self.as_csv
    CSV.generate do |csv|
      columns = %w(id url name facebook vk incamp_url ml_url dt_url bc_url pd_url inlearno_url created_at updated_at company_id preview program study accommodation meal security pricing adds latitude longitude starting_age finish_age foundation_year kids_in_camp kids_in_group leaders_per_group promo_day photos video_links comment schedule user_id presentation has_incamp_price group_leader_anounce)
      csv << columns.map(&:humanize)
      Camp.find_each do |c|
        csv << c.attributes.values_at(*columns)
      end
    end
  end

  def self.next_camp_for_edition(user_id)
    # should be added choosing the same organization later
    camp = Camp.where('user_id = ? AND (is_finished IS NULL OR is_finished = FALSE)', user_id) #already started camp
    if camp.blank?
      select_clause = 'DISTINCT camps.*'
      from_clause = 'camps, camps as other_camps'
      where_clause = 'camps.company_id = other_camps.company_id and camps.user_id = ? and camps.is_finished = TRUE and other_camps.is_finished IS NULL'
      camp = Camp.select(select_clause).where(where_clause, user_id).from(from_clause).all
      camp = Camp.where('is_finished IS NULL') if camp.blank?
      return nil if camp.blank?
    end
    camp.first
  end

  def fullness
    score = 0
    max_score = 37
    score += 1 unless presentation.nil?
    score += 2 unless preview.blank?
    score += 2 unless program.blank?
    score +=2 unless study.blank?
    score +=2 unless schedule.blank?
    score +=2 unless accommodation.blank?
    score +=1 unless meal.blank?
    score +=2 unless security.blank?
    score +=1 unless seasonships.blank?
    score +=1 unless camp_categories.blank?
    score +=1 unless pricing.blank?
    score +=1 unless adds.blank?
    score +=1 unless latitude.blank?
    score +=1 unless longitude.blank?
    score +=1 unless geotags.blank?
    score +=1 unless starting_age.blank?
    score +=1 unless finish_age.blank?
    score +=1 unless foundation_year.blank?
    score +=1 unless kids_in_camp.blank?
    score +=1 unless kids_in_group.blank?
    score +=1 unless leaders_per_group.blank?
    score +=1 unless promo_day.nil?
    score +=1 unless photos.blank?
    score +=1 unless video_links.blank?
    score +=2 unless group_leader_anounce.blank?
    score +=2 unless group_leaders.blank?
    score +=2 unless reviews.blank?
    score +=1 unless is_finished.nil?
    full = score.to_f / max_score
    fl = full * 100
    return fl.to_i
  end
end

app/models/camp_category.rb
class CampCategory < ApplicationRecord
  has_many :categorizations
  has_many :camps, through: :categorizations
  validates :name, presence: true
end

app/models/camp_shift.rb
class CampShift < ApplicationRecord
  belongs_to :camp
  #validates :camp_id, uniqueness: { scope: { :start, :finish, :price } }
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :camps
  has_many :content_camps, through: :camps

  validates :name, :entity, presence: true
end

app/models/geotag.rb
class Geotag < ApplicationRecord
  has_many :taggizations
  has_many :camps, through: :taggizations
  validates :name, uniqueness: true, presence: true
end

app/models/group_leader.rb
class GroupLeader < ApplicationRecord
  belongs_to :camp
end

app/models/iteration.rb
class Iteration < ApplicationRecord
  has_many :camps
end

app/models/rating_change.rb
class RatingChange < ApplicationRecord
  belongs_to :user
  belongs_to :rating_change_type
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :review_role
  belongs_to :camp
end

app/models/review_role.rb
class ReviewRole < ApplicationRecord
  has_many :reviews
  validates :name, presence: true
end

app/models/season_type.rb
class SeasonType < ApplicationRecord
  has_many :seasonships
  has_many :camps, through: :seasonships
end

app/models/seasonship.rb
class Seasonship < ApplicationRecord
  belongs_to :season_type
  belongs_to :camp
  validates :camp_id, uniqueness: { scope: :season_type_id }
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :badge
  has_many :users
end

app/models/taggization.rb
class Taggization < ApplicationRecord
  belongs_to :camp
  belongs_to :geotag
  #validates :camp_id, uniqueness: { scope: :geotag_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #attr_accessor :name

  belongs_to :user_role
  has_many :camps
  has_many :rating_changes

  belongs_to :status
  before_validation :default_role


  def is_admin?
    user_role.name == "admin"
  end


  private

  def default_role
    self.user_role ||= UserRole.find_by_name('user')
    self.status ||= Status.first
    self.rating ||= 0
  end

end

app/models/user_role.rb
class UserRole < ApplicationRecord
  has_many :users
end

app/models/week_result.rb
class WeekResult < ApplicationRecord
  belongs_to :user
  belongs_to :camp
end

app/helpers/camps_helper.rb
module CampsHelper
  def camp_full_name_hash
    {
      url: 'Сайт лагеря',
      facebook: 'Группа в фб',
      vk: 'Группа в ВК',
      incamp_url: 'Страница на Incamp',
      ml_url: 'Страница на mir-lagerey',
      dt_url: 'Страница на deti-travel',
      inlearno_url: 'Страница на Inlearno',
      bc_url: 'Страница на best-camps',
      pd_url: 'Страница на poehali-deti',
      preview: 'Анонс лагеря',
      program: 'Общая программа',
      study: 'Обучение',
      schedule: 'Распорядок дня',
      accommodation: 'Размещение/территория',
      meal: 'Питание',
      security: 'Безопасность/медицина',
      pricing: 'Что входит в стоимость',
      adds: 'Адрес',
      latitude: 'Широта',
      longitude: 'Долгота',
      starting_age: 'С какого возраста',
      finish_age: 'До какого возраста',
      foundation_year: 'Год основания',
      kids_in_camp: 'Детей в лагере',
      kids_in_group: 'Детей в отряде',
      leaders_per_group: 'Вожатых на отряд',
      promo_day: 'Наличие дня открытых дверей',
      photos: 'Качество фотографий',
      video_links: 'Ссылки на видео',
      comment: 'Общий комментарий',
      is_finished: 'Заполнение анкеты окончено'
    }
  end

  def camp_admin_name_hash
    {
        url: 'Сайт лагеря',
        facebook: 'Группа в фб',
        vk: 'Группа в ВК',
        incamp_url: 'Страница на Incamp',
        ml_url: 'Страница на mir-lagerey',
        dt_url: 'Страница на deti-travel',
        inlearno_url: 'Страница на Inlearno',
        bc_url: 'Страница на best-camps',
        pd_url: 'Страница на poehali-deti'
    }
  end


end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to "Contenter", root_path, class: "navbar-brand"
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      - if user_signed_in?
        %li.nav-item
          - if current_user.is_admin?
            = link_to 'Компании', companies_path, class: 'nav-link'
          - else
            = link_to 'Новый лагерь', new_camp_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Все лагеря', camps_path, class: 'nav-link'
        %li.nav-item
          - if current_user.is_admin?
            = link_to 'Статистика', camp_statistics_path, class: 'nav-link'
        %li.nav-item
          - if current_user.is_admin?
            = link_to 'Выплаты', camp_payments_path, class: 'nav-link'
        - if current_user.is_admin?
          %li.nav-item.dropdown
            %a#downloads.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Downloads
            .dropdown-menu{"aria-labelledby" => "downloads"}
              = link_to 'Download Camps CSV', camps_path(format: :csv), class: 'dropdown-item'
              = link_to 'Организации', downloads_path(format: :csv, type: 'companies'), class: 'dropdown-item'
              = link_to 'Смены', downloads_path(format: :csv, type: 'shifts'), class: 'dropdown-item'
              = link_to 'Seasonship', downloads_path(format: :csv, type: 'seasonship'), class: 'dropdown-item'
              = link_to 'Seasons', downloads_path(format: :csv, type: 'seasons'), class: 'dropdown-item'
              = link_to 'Taggization', downloads_path(format: :csv, type: 'taggization'), class: 'dropdown-item'
              = link_to 'Tags', downloads_path(format: :csv, type: 'geotags'), class: 'dropdown-item'
              = link_to 'Leaders', downloads_path(format: :csv, type: 'leaders'), class: 'dropdown-item'
              = link_to 'Reviews', downloads_path(format: :csv, type: 'reviews'), class: 'dropdown-item'
              = link_to 'Review Roles', downloads_path(format: :csv, type: 'reviewroles'), class: 'dropdown-item'
              = link_to 'Categorization', downloads_path(format: :csv, type: 'categorization'), class: 'dropdown-item'
              = link_to 'Camp categories', downloads_path(format: :csv, type: 'campcategories'), class: 'dropdown-item'
    %ul.navbar-nav.ml-auto
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          = user_signed_in? ? (current_user.name || current_user.email) : 'Log in'
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          - if user_signed_in?
            = link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item'
            = link_to 'Show profile', current_user, class: 'dropdown-item'
            .dropdown-divider
            = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item'
          - else
            = link_to 'Sign up', new_user_registration_path, class: 'dropdown-item'
            = link_to 'Log in', new_user_session_path, class: 'dropdown-item'
      - if user_signed_in?
        %li
          = image_tag current_user.status.badge.main_picture, class: "rounded-circle align-middle border", style: 'width: 40px; height: 40px;'

app/views/layouts/_user_payments.html.haml
.card{style: 'margin-top: 10px; padding: 10px 0px;'}
  .row
    .col-md-4
      = image_tag user.status.badge.main_picture, style: 'width: 100%; height: auto;'
    .col-md-4
      %ul.list-unstyled
        %li Name: #{user.name}
        %li Email: #{user.email}
        %li Status: #{user.status.badge.name || 'No status'}
        %li Current rating: #{user.rating || 'No rating'}
        %li Rating length: #{user.status.length || 'No data for this status'}
        %li Next rating change: #{user.status.whole_length || 'No data for this status'}
        %li To next rating: #{user.status.whole_length - user.rating || 'No data for this status'}
        %li Next status: #{ user.status.next_status_id.nil? ? 'No data for next status' : (Status.find_by(id: user.status.next_status_id).badge.name || 'No data for next status')}
        %li Camps assigned: #{Camp.where(user: user).count || 'No info'}
        %li Camps finished: #{Camp.where(user: user, is_finished: 1).count || 'No info'}
        %li Camps approved: #{Camp.where(user: user, is_approved: 1).count || 'No info'}
        %li Last sign in at: #{user.current_sign_in_at || 'No info'}
    .col-md-4
      %ul.list-unstyled
        %li Current status camp payment: #{(user.status.pay_coefficient*100).round(0)}р.
        %li Next status camp payment: #{ user.status.next_status_id.nil? ? 'No data for next status' : (Status.find_by(id: user.status.next_status_id).pay_coefficient*100).round(0).to_s + 'р.' }

%div{style: 'padding: 5px;'}
  - user.camps.where(is_rated_for_approving: 1).order(created_at: :desc).to_a.each do |c|
    .row
      .col-md-2
        %p.small=c.id
      .col-md-2
        %p.small=c.updated_at.strftime("%F, %T")
      .col-md-6
        %p.small=c.name
      .col-md-2
        %p.small=(c.pay_coefficient*100).round(2).to_s + 'р.'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contenter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container" >
      <% if !flash.empty? %>
        <div class="container">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>

</html>